### ISSUE TITLE
esp8266 +  VL53L1X  init failed

### ISSUE THREAD

**Issue by neolu** [pololu/vl53l1x-st-api-arduino#10]
VL53L1X Model_ID: EF
VL53L1X Module_Type: EF
VL53L1X: EFFE
Autonomous Ranging Test
VL53L1_StartMeasurement failed

**Comment by kevin-pololu** [comment]
If you are still looking for help troubleshooting this, please post on [the Pololu forum](https://forum.pololu.com/) and include pictures showing your connections. (The GitHub issues are intended for tracking specific problems with and feature requests for the software, and this does not currently appear to indicate a bug in the code itself.)
