### ISSUE TITLE
Won't upload to board. Invalid library

### ISSUE THREAD

**Issue by wightga** [pololu/vl53l1x-st-api-arduino#4]
When I try to upload to my Arduino Uno, It gives me these errors.

Arduino: 1.8.5 (Windows 7), Board: "Arduino/Genuino Uno"

Sketch uses 20530 bytes (63%) of program storage space. Maximum is 32256 bytes.
Global variables use 1316 bytes (64%) of dynamic memory, leaving 732 bytes for local variables. Maximum is 2048 bytes.
avrdude: ser_open(): can't open device "\\.\COM5": Access is denied.

Problem uploading to board.  See http://www.arduino.cc/en/Guide/Troubleshooting#upload for suggestions.
Invalid library found in C:\Users\wightga\Documents\Arduino\libraries\vl53l1x-st-api-arduino-master: C:\Users\wightga\Documents\Arduino\libraries\vl53l1x-st-api-arduino-master
Invalid library found in C:\Users\wightga\Documents\Arduino\libraries\vl53l1x-st-api-arduino-master: C:\Users\wightga\Documents\Arduino\libraries\vl53l1x-st-api-arduino-master

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

Let me know what you think

**Comment by wightga** [comment]
It uploaded now but it still says that there are invalid libraries.  Also, how do I go about changing the ROI?

**Comment by kevin-pololu** [comment]
Could you post the exact error message you are seeing about invalid libraries?

We haven't tried configuring the ROI, but I suggest looking at section 2.5.6 of the API user's guide, which talks about the `VL53L1_SetUserROI()` function. The user's guide can be found in the API downloaded from ST.

**Comment by wightga** [comment]
Here is what is being said about invalid libraries.

Invalid library found in C:\Users\wightga\Documents\Arduino\libraries\vl53l1x-st-api-arduino-master: C:\Users\wightga\Documents\Arduino\libraries\vl53l1x-st-api-arduino-master
Invalid library found in C:\Users\wightga\Documents\Arduino\libraries\vl53l1x-st-api-arduino-master: C:\Users\wightga\Documents\Arduino\libraries\vl53l1x-st-api-arduino-master

I will look up to try and figure out configuring the ROI.  The plan is to use multiple sensors in an array that analyze a stream of concrete for air bubbles. The idea is that more sensors at a closer range and with a smaller ROI will have a higher resolution.

**Comment by kevin-pololu** [comment]
This API implementation is not a library, so you should not put it in the libraries subfolder of your Arduino sketchbook folder. If you move it elsewhere, it should stop that warning from showing up.
