### ISSUE TITLE
Memory problems with ClearInterruptAndStartMeasurment

### ISSUE THREAD

**Issue by acegas** [pololu/vl53l1x-st-api-arduino#6]
Hi
I need to make an array using 20 vl53l1x.  I'm using this library instead of the streamlined because I need to define the ROI.  I'm finding that calling the function ( status = VL53L1_ClearInterruptAndStartMeasurement(Dev); ) consumes a significant amount of memory.  So much that setting up all 20 and getting measurements for only 2 of the 20 fills up more than 200% of the sram memory on an Arduino Mega 2560 during building.  
However if I don't call the function the memory consumption is manageable.   The documentation specifies that we do need to call it in order to get accurate readings.  Any idea why this is happening?  or an alternative to resetting the data ready flag?

**Comment by kevin-pololu** [comment]
It looks like you [posted this question to our forum](https://forum.pololu.com/t/multiple-vl53l1x-and-memory-problems/15686) and I replied to you there, so I am closing this GitHub issue.
